export {
  isGitHubUrl,
  parseGitHubUrl,
  isGitRepository,
  isBareGitRepository,
  getCurrentBranch,
  listBranches,
  listRemoteBranches,
  fetchRemote,
  getBranchInfo,
  getBranchStatus,
  checkoutBranch,
  deleteBranch,
  pullBranch,
  resetLocalChanges,
  getRemoteUrl,
  getRepoStatus,
  getRepoChanges,
  getRepoFileDiff,
  getRepoCommitChanges,
  getRepoCommitDiff,
  getRepoDeliveryStatus,
  getRepoRefSha,
  parseGitStatusPorcelain,
  getCloneBaseDir,
  repoToDirName,
  dirNameToRepo,
  listClonedRepos,
  normalizeLocalRepoPath,
  validateRepoInput,
  validateBranchName,
  sanitizeBranchName,
  type ParsedGitHubUrl,
  type RepoBranchInfo,
  type RepoStatus,
  type RepoChanges,
  type RepoFileDiff,
  type RepoCommitChange,
  type RepoCommitDiff,
  type RepoDeliveryStatus,
  type GitFileChange,
  type FileChangeStatus,
  type BranchStatus,
  type BranchValidationResult,
  type ClonedRepoInfo,
  type ValidationResult,
  type LocalFolderErrorCode,
} from "./git-utils";

export {
  isGitAuthError,
  isSSHAuthError,
  isHTTPSAuthError,
  getGitAuthErrorType,
  getGitAuthErrorMessage,
  getGitCredentialSetupInstructions,
  getGitErrorMessage,
  withGitAuthHandling,
  type GitAuthErrorType,
  type GitCredentialInstructions,
  type GitOperationResult,
} from "./git-error-handler";

export {
  stageFiles,
  unstageFiles,
  discardChanges,
  createCommit,
  pullCommits,
  rebaseBranch,
  resetBranch,
  getCommitList,
  getFileDiff,
  getCommitDiff,
  type CommitInfo,
} from "./git-operations";
